controller_list:
  - name: fake_robot_controller
    joints:
      - a1
      - a2
      - a3
      - a4
      - a5
      - a6
  - name: fake_bumblebee_controller
    joints:
      - a1
      - a2
      - a3
      - a4
      - a5
      - a6